# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Edicion_Btn
                                 A QGIS plugin
 Este Plugin Permite la descarga y edicion controlada de la BTN
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-11
        copyright            : (C) 2023 by Antonio Moreno Palacios
        email                : ammorenopalacios@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Edicion_Btn class from file Edicion_Btn.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .edicion_btn import Edicion_Btn
    return Edicion_Btn(iface)
